//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Yahtzee"",
            ""id"": ""d65663e2-b080-4ed1-8119-576c9ab030a0"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""b4c7fbb1-4bf7-4c2b-87b3-8ba7ada1114b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""64ca9924-4ed8-4b38-88d5-7a2cc6db05d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""3923f0cb-6712-4239-85c1-16106e35fbc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""7bd529a3-3ccd-4b28-bdfa-fdd4df6ab83a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bb1d1b3b-e383-4187-af22-297cea49f952"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64ffa0d1-70e3-4e0d-8f4a-266ea8218ea8"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1aea1e5a-3764-44c3-bf57-90d6bb560798"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ee2f39d-9fd6-491c-aa13-743c1e9acef3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Yahtzee
        m_Yahtzee = asset.FindActionMap("Yahtzee", throwIfNotFound: true);
        m_Yahtzee_Select = m_Yahtzee.FindAction("Select", throwIfNotFound: true);
        m_Yahtzee_Restart = m_Yahtzee.FindAction("Restart", throwIfNotFound: true);
        m_Yahtzee_Quit = m_Yahtzee.FindAction("Quit", throwIfNotFound: true);
        m_Yahtzee_Save = m_Yahtzee.FindAction("Save", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Yahtzee
    private readonly InputActionMap m_Yahtzee;
    private List<IYahtzeeActions> m_YahtzeeActionsCallbackInterfaces = new List<IYahtzeeActions>();
    private readonly InputAction m_Yahtzee_Select;
    private readonly InputAction m_Yahtzee_Restart;
    private readonly InputAction m_Yahtzee_Quit;
    private readonly InputAction m_Yahtzee_Save;
    public struct YahtzeeActions
    {
        private @PlayerInputActions m_Wrapper;
        public YahtzeeActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Yahtzee_Select;
        public InputAction @Restart => m_Wrapper.m_Yahtzee_Restart;
        public InputAction @Quit => m_Wrapper.m_Yahtzee_Quit;
        public InputAction @Save => m_Wrapper.m_Yahtzee_Save;
        public InputActionMap Get() { return m_Wrapper.m_Yahtzee; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(YahtzeeActions set) { return set.Get(); }
        public void AddCallbacks(IYahtzeeActions instance)
        {
            if (instance == null || m_Wrapper.m_YahtzeeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_YahtzeeActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Restart.started += instance.OnRestart;
            @Restart.performed += instance.OnRestart;
            @Restart.canceled += instance.OnRestart;
            @Quit.started += instance.OnQuit;
            @Quit.performed += instance.OnQuit;
            @Quit.canceled += instance.OnQuit;
            @Save.started += instance.OnSave;
            @Save.performed += instance.OnSave;
            @Save.canceled += instance.OnSave;
        }

        private void UnregisterCallbacks(IYahtzeeActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Restart.started -= instance.OnRestart;
            @Restart.performed -= instance.OnRestart;
            @Restart.canceled -= instance.OnRestart;
            @Quit.started -= instance.OnQuit;
            @Quit.performed -= instance.OnQuit;
            @Quit.canceled -= instance.OnQuit;
            @Save.started -= instance.OnSave;
            @Save.performed -= instance.OnSave;
            @Save.canceled -= instance.OnSave;
        }

        public void RemoveCallbacks(IYahtzeeActions instance)
        {
            if (m_Wrapper.m_YahtzeeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IYahtzeeActions instance)
        {
            foreach (var item in m_Wrapper.m_YahtzeeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_YahtzeeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public YahtzeeActions @Yahtzee => new YahtzeeActions(this);
    public interface IYahtzeeActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnRestart(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
        void OnSave(InputAction.CallbackContext context);
    }
}
